kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: acme-dns-service-vol
  namespace: kube-system
  labels:
    app: acme-dns-service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
